### ISSUE TITLE
Mixing old and new values when updating level set?

### ISSUE THREAD

**Issue by mnocon** [rcrandall/ChanVese#2]
Hello,

I have a question (or perhaps an issue) with how the level set is updated. 
In function "ChanVeseSegmentation", lines 306-311 ([https://github.com/rcrandall/ChanVese/blob/master/ChanVeseSegmentation.cpp#L306]
we are updating value of phi basing on values of its neighbours (and calculated coefficients), but we are not using a copy of level set values, that means that the neighbours we've already processed are influencing the next values.

Shouldn't the new level set be calculated using a copy of the current one (which will keep its values contant)? In the current implementation we're calculating phi(i+1) using mixed values (some already from phi(i+1), some from phi(i)).

If you could confirm that that is indeed the case I will try to submit a PR (once I have some free time on my hands).

**Comment by rcrandall** [comment]
Hi Marek,

Sorry for the delayed response. It's been a long time since I looked at
this code, but it does seem like that's probably an error. I might have
some time to look at it more carefully this weekend, or if you've tried it
with a copy of Phi I'd be interested to know if there's a noticeable
difference in the result.

Thanks!
-Robert

**Comment by mnocon** [comment]
Hello Robert,

thank you for the reply. In the meantime I've found an article called "Chan–Vese Segmentation" written by Pascal Getreuer (available at: http://www.ipol.im/pub/art/2012/g-cv/article.pdf), in which Equations 21 and 21 state "The values ϕi,j , ϕi−1,j , ϕi,j−1 are evaluated at timestep n + 1 and all others at timestep n".
I haven't compared it to the algorithm used in your project, but I suspect it's a similar (correct) implementation.

It looks like this "issue" is in fact not an issue but me missing this implementation detail, sorry for bothering you :)

Regards,
Marek

**Comment by yash001** [comment]
@rcrandall @mnocon  please tell me step by step process of how to run this code ?
